#!/bin/bash

USER="nodered"
PASSWORD="nodered"

useradd $USER -s /bin/bash -m
echo $USER:$PASSWORD | chpasswd

echo "[Unit]
Description=Node-RED
After=syslog.target network.target

[Service]
ExecStart=/usr/bin/node-red-pi --max-old-space-size=128 -v
Restart=on-failure
KillSignal=SIGINT

# log output to syslog as 'node-red'
SyslogIdentifier=node-red
StandardOutput=syslog

# non-root user to run as
WorkingDirectory=/home/$USER/
User=$USER
Group=$USER

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/node-red.service

systemctl enable node-red
systemctl start node-red
